version: '3'

services:
  web:
    image: php:7.4-apache
    container_name: apache-php-container
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.6.51
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: notebook
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: